GET http://localhost:3000/tasks

###

POST http://localhost:3000/tasks Content-Type: application/json

{
    "name": "Kyle", "paassword": "password"
}

###

POST http://localhost:3000/task/login Content-Type: application/json

{
"name": "Kyle", "password": "password"
}